apiVersion: apps/v1
kind: Deployment
metadata:
  name: task-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: task-service
  template:
    metadata:
      labels:
        app: task-service
    spec:
      containers:
      - name: task-service
        image: fatianbilal/task-service:latest
        ports:
        - containerPort: 3001
        env:
        - name: USER_SERVICE_URL
          value: "http://user-service"
        - name: DB_HOST
          value: "task-postgres"
        - name: DB_USER
          value: "postgres"
        - name: DB_PASSWORD
          value: "password"
        - name: DB_NAME
          value: "taskdb"