apiVersion: v1
kind: Service
metadata:
  name: task-service
  namespace: mini-todo
spec:
  selector:
    app: task-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3001
  type: ClusterIP